### ISSUE TITLE
deparse can't handle Grouping Sets

### ISSUE THREAD

**Issue by primeapple** [pganalyze/pg_query#126]
Hey everyone,

I found another issue with the deparse() function.
This time it is about Grouping Sets and Operators like Drill Down and Roll Up, see: https://www.postgresql.org/docs/devel/queries-table-expressions.html#QUERIES-GROUPING-SETS

Example:
```
PgQuery.parse("SELECT brand, size, sum(sales) FROM items_sold GROUP BY GROUPING SETS ((brand), (size), ());").deparse
Traceback (most recent call last):
       15: from /usr/bin/irb:23:in `<main>'
       14: from /usr/bin/irb:23:in `load'
       13: from /usr/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
       12: from (irb):2
       11: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:6:in `deparse'
       10: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:6:in `map'
        9: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:7:in `block in deparse'
        8: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:18:in `from'
        7: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:130:in `deparse_item'
        6: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:200:in `deparse_raw_stmt'
        5: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:138:in `deparse_item'
        4: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:810:in `deparse_select'
        3: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:810:in `map'
        2: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:811:in `block in deparse_select'
        1: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:182:in `deparse_item'
RuntimeError (Can't deparse: GroupingSet: {"kind"=>4, "content"=>[{"ColumnRef"=>{"fields"=>[{"String"=>{"str"=>"brand"}}], "location"=>72}}, {"ColumnRef"=>{"fields"=>[{"String"=>{"str"=>"size"}}], "location"=>81}}, {"GroupingSet"=>{"kind"=>0, "location"=>88}}], "location"=>56})
```

The same is with RollUp and Cube:
```
PgQuery.parse("SELECT brand, sum(sales) FROM items_sold GROUP BY CUBE (brand);").deparse
Traceback (most recent call last):
       16: from /usr/bin/irb:23:in `<main>'
       15: from /usr/bin/irb:23:in `load'
       14: from /usr/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
       13: from (irb):6
       12: from (irb):6:in `rescue in irb_binding'
       11: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:6:in `deparse'
       10: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:6:in `map'
        9: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:7:in `block in deparse'
        8: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:18:in `from'
        7: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:130:in `deparse_item'
        6: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:200:in `deparse_raw_stmt'
        5: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:138:in `deparse_item'
        4: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:810:in `deparse_select'
        3: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:810:in `map'
        2: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:811:in `block in deparse_select'
        1: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:182:in `deparse_item'
```

**Comment by lfittl** [comment]
@primeapple Late reply, but this has been fixed now in the 2.0 release!

```
irb(main):004:0> PgQuery.parse("SELECT brand, size, sum(sales) FROM items_sold GROUP BY GROUPING SETS ((brand), (size), ());").deparse
=> "SELECT brand, size, sum(sales) FROM items_sold GROUP BY GROUPING SETS (brand, size, ())"
irb(main):005:0> PgQuery.parse("SELECT brand, sum(sales) FROM items_sold GROUP BY CUBE (brand);").deparse
=> "SELECT brand, sum(sales) FROM items_sold GROUP BY CUBE (brand)"
```
