### ISSUE TITLE
On OpenBSD/ad 7.4 pg_query generates the error `Unable to resolve symbol - Init_pg_query`

### ISSUE THREAD

**Issue by vtamara** [pganalyze/pg_query#315]
My platform is:
```sh
% uname -a
OpenBSD mi.mi.org 7.4 APRENDIENDODEJESUS.MP#7 amd64
% ruby -v
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-openbsd]
% psql --version
psql (PostgreSQL) 16.2
```

I installed with:
```
% doas gem install pg_query
Fetching google-protobuf-4.26.1.gem
Fetching pg_query-5.1.0.gem
Building native extensions. This could take a while...
Successfully installed google-protobuf-4.26.1
Building native extensions. This could take a while...
Successfully installed pg_query-5.1.0
Parsing documentation for google-protobuf-4.26.1
Installing ri documentation for google-protobuf-4.26.1
Parsing documentation for pg_query-5.1.0
Installing ri documentation for pg_query-5.1.0
Done installing documentation for google-protobuf, pg_query after 2 seconds
2 gems installed
```

The minimal example I'm using in a file `e.rb` is:

```rb
require "pg_query"
puts PgQuery.parse("SELECT 1").inspect 
```

Running with `ruby e.rb` produces:

```
<internal:/usr/local/lib/ruby/site_ruby/3.3/rubygems/core_ext/kernel_require.rb>:136:in `require': Unable to resolve symbol - Init_pg_query (LoadError)
        from <internal:/usr/local/lib/ruby/site_ruby/3.3/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from /usr/local/lib/ruby/gems/3.3/gems/pg_query-5.1.0/lib/pg_query.rb:7:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/site_ruby/3.3/rubygems/core_ext/kernel_require.rb>:141:in `require'
        from <internal:/usr/local/lib/ruby/site_ruby/3.3/rubygems/core_ext/kernel_require.rb>:141:in `rescue in require'
        from <internal:/usr/local/lib/ruby/site_ruby/3.3/rubygems/core_ext/kernel_require.rb>:135:in `require'
        from e.rb:1:in `<main>'
<internal:/usr/local/lib/ruby/site_ruby/3.3/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- pg_query (LoadError)
        from <internal:/usr/local/lib/ruby/site_ruby/3.3/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from e.rb:1:in `<main>'
```

Any suggestions how to diagnose better or how to solve?

**Comment by lfittl** [comment]
This should have been resolved with the [6.0.0](https://github.com/pganalyze/pg_query/blob/main/CHANGELOG.md#600-----2024-11-26) release, that includes the fix from https://github.com/pganalyze/pg_query/pull/313

**Comment by vtamara** [comment]
That fix seems particular for FreeBSD

Trying today on OpenBSD/adJ 7.6 with pg_query-6.0.0 produces the same result:

```
<internal:/usr/local/lib/ruby/site_ruby/3.4/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require': Unable to resolve symbol - Init_pg_query (LoadError)
        from <internal:/usr/local/lib/ruby/site_ruby/3.4/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
        from /usr/local/lib/ruby/gems/3.4/gems/pg_query-6.0.0/lib/pg_query.rb:7:in '<top (required)>'
        from <internal:/usr/local/lib/ruby/site_ruby/3.4/rubygems/core_ext/kernel_require.rb>:141:in 'Kernel#require'
        from <internal:/usr/local/lib/ruby/site_ruby/3.4/rubygems/core_ext/kernel_require.rb>:141:in 'Kernel#require'
        from ej.rb:1:in '<main>'
<internal:/usr/local/lib/ruby/site_ruby/3.4/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require': cannot load such file -- pg_query (LoadError)
        from <internal:/usr/local/lib/ruby/site_ruby/3.4/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
        from ej.rb:1:in '<main>'
```

**Comment by lfittl** [comment]
> That fix seems particular for FreeBSD
> 
> Trying today on OpenBSD/adJ 7.6 with pg_query-6.0.0 produces the same result:

Thanks for confirming this is

**Comment by vtamara** [comment]
> I wonder if the if condition here needs to be expanded to include `openbsd`: https://github.com/pganalyze/pg_query/blob/main/ext/pg_query/extconf.rb#L37

You Right
